apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticketing-dev-393813/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ticketing-dev-393813
manifests:
  rawYaml:
    - ./infra/k8s/*